### ISSUE TITLE
Question for the zero-shot method evaluation on swig dataset

### ISSUE THREAD

**Issue by ChelsieLei** [ltttpku/CMD-SE-release#2]
Hi @ltttpku,

Thanks for your nice work! I saw in your supplementary materials, you provided the results of the HOICLIP model trained on HICO-DET and tested on swig. However, HOICLIP requires the pre-defined HOI classes to obtain the verb representation (shown in Fig. 4 in HOICLIP paper), which is used in the HOI prediction. How do you deal with this problem? Thanks a lot!

**Comment by ltttpku** [comment]
Thanks for your interest in our work! We provide the model with predefined HOI classes during inference.

**Comment by ChelsieLei** [comment]
Hi, thank you for your reply. 
HOICLIP has a verb classifier that requires the pre-defined unseen classes in training. However, based on the open-vocabulary setting, the unseen classes are only available after training and before inference. Thus, I wonder how you solve this problem when testing HICODET on the SWIG dataset which has unseen classes after the HOICLIP training.

**Comment by ltttpku** [comment]
I remember that I trained HOICLIP on the HICO-DET dataset, using all HOI classes from HICO-DET by default. During testing, I replaced the embeddings with those from SWIG-HOI.

**Comment by ChelsieLei** [comment]
Hi, I mean this module in red circle requires the unseen class information. How do you use the verb classifier? The code of the verb implementation is here [https://github.com/Artanic30/HOICLIP/blob/main/models/models_hoiclip/hoiclip.py#L202]
<img width="928" alt="image" src="https://github.com/ltttpku/CMD-SE-release/assets/122675401/13aa036e-e7a8-471d-a1e3-08f2343779aa">

**Comment by ltttpku** [comment]
The verb classifier was discarded due to the lack of data for `visual semantic arithmetic`.

**Comment by ChelsieLei** [comment]
Thanks for your information!
