### ISSUE TITLE
Experimental results on HICO-DET

### ISSUE THREAD

**Issue by jiayuancs** [ltttpku/CMD-SE-release#4]
Hi，thank you for your nice work!

I downloaded the [HICO-DET checkpoint](https://disk.pku.edu.cn/link/AACBAE087FC3C7479EBD955966748D6F3F) according to the [README](https://github.com/ltttpku/CMD-SE-release?tab=readme-ov-file#models) for testing. But the results obtained do not match those reported in your paper.

Here are my results obtained using [HICO-DET checkpoint](https://disk.pku.edu.cn/link/AACBAE087FC3C7479EBD955966748D6F3F): 

```
Averaged stats: class_error: 50.00  loss: 7.2169 (7.1753)  loss_ce: 3.3509 (3.2271)  loss_bbox: 1.8442 (1.8078)  loss_giou: 1.7364 (1.8125)  loss_conf: 0.2873 (0.3279)  loss_ce_unscaled: 0.6702 (0.6454)  class_error_unscaled: 29.6296 (28.5743)  loss_bbox_unscaled: 0.3688 (0.3616)  loss_giou_unscaled: 0.8682 (0.9062)  loss_conf_unscaled: 0.0287 (0.0328)
zero-shot mAP: 15.44
seen mAP: 23.47
full mAP: 21.69
```

Here are the results reported in your paper:

| dataset | HOI Tokens | Unseen | Seen | Full |
| :-----: | :-----: | :-----: | :-----: | -----: |
| HICO-DET | 25 | 16.70 | 23.95 | 22.35 |

Is the checkpoint provided in readme the latest version?

**Comment by ltttpku** [comment]
Hi, I used the latest checkpoint provided in the README for HICO-DET again and obtained the following results:
```
Averaged stats: class_error: 46.15  loss: 7.3331 (7.0990)  loss_ce: 3.4087 (3.1786)  loss_bbox: 1.8379 (1.7957)  loss_giou: 1.7631 (1.8012)  loss_conf: 0.2771 (0.3234)  loss_ce_unscaled: 0.6817 (0.6357)  class_error_unscaled: 29.6296 (28.1716)  loss_bbox_unscaled: 0.3676 (0.3591)  loss_giou_unscaled: 0.8816 (0.9006)  loss_conf_unscaled: 0.0277 (0.0323)
zero-shot mAP: 16.75
seen mAP: 24.00
full mAP: 22.39
```

The evaluation is conducted on a 3090 GPU using the following command:
```
python -m torch.distributed.launch --nproc_per_node=1 --master_port 3990 --use_env main.py \
    --batch_size 64 \
    --output_dir checkpoints \
    --epochs 80 \
    --lr 1e-4 --min-lr 1e-7 \
    --hoi_token_length 25 \
    --enable_dec \
    --dataset_file hico --multi_scale true --f_idxs 5 8 11 --set_cost_hoi_type 5 --use_aux_text true \
    --enable_focal_loss --description_file_path hico_hoi_descriptions.json \
    --eval --pretrained checkpoints/hico-checkpoint0075.pth
```

**Comment by jiayuancs** [comment]
Thank you for your reply. Could you tell me your version of PyTorch? I'm thinking there might be an issue with my environment.

**Comment by ltttpku** [comment]
Hi, I am using PyTorch 1.13.1+cu116 in my environment.

**Comment by jiayuancs** [comment]
Thanks for your information!
