### ISSUE TITLE
Demo code

### ISSUE THREAD

**Issue by YangJae96** [ltttpku/CMD-SE-release#5]
HI. Thanks for the great work!

Is there a demo code that we can use it for image inference?

Thanks.

**Comment by ltttpku** [comment]
Hi, I’m currently tied up with other tasks. However, you might find it helpful to use the [evaluation function](https://github.com/ltttpku/CMD-SE-release/blob/main/engine.py#L73) to write a demo code—it should be fairly straightforward.
